### ISSUE TITLE
View login e redefinir senha

### ISSUE THREAD

**Issue by dendo1234** [EdPPF/CAMAAR#45]
Será renderizado pela Controller usuário
sugestão:
User#login
User#update
#36

**Comment by llaurxx** [comment]
![loginPagina](https://github.com/EdPPF/CAMAAR/assets/65201622/8ccb31d4-ac0f-473c-90a0-2745f3ae24b5)

**Comment by llaurxx** [comment]
![image](https://github.com/EdPPF/CAMAAR/assets/65201622/6130151a-fa68-40a4-a108-073397edba09)
